sudo: false
language: python
python:
- '3.4'
script:
- ./waf configure clean build dist
- pushd build
- md5sum "script.module.pycountry-17.1.8.zip" > "script.module.pycountry-17.1.8.zip.md5"
- popd
before_deploy:
- mkdir -p dist/
- cp build/*.zip build/*.zip.md5 build/addon.xml icon.png dist/
deploy:
  provider: s3
  access_key_id: "${AWS_KEY_ID}"
  secret_access_key: "${AWS_ACCESS_KEY}"
  bucket: xbmc.beardypig.plugins
  local-dir: dist
  upload-dir: addons/script.module.pycountry
  skip_cleanup: true
  on:
    repo: beardypig/script.module.pycountry
    tags: true

after_deploy:
- gem install travis
- curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
- sh trigger-travis.sh beardypig xbmc.beardypig.plugins $TRAVIS_ACCESS_TOKEN
